---
apiVersion: v1
kind: Pod
metadata:
  name: 14.3-netology-fedora
spec:
  containers:
  - name: fedora
    image: fedora
    command: ['sleep', 'infinity']
    env:
    - name: DOMAIN
      valueFrom:
        configMapKeyRef:
          name: 14.3-netology-configmap
          key: domain
    volumeMounts:
    - name: config-volume
      mountPath: /opt/config.conf
      subPath: config.conf
  volumes:
  - name: config-volume
    configMap:
      name: 14.3-netology-configmap
